"""Add processing_stage and processing_step to document_analyses

Revision ID: 8d56f94fed2e
Revises: 9a81552f7f7e
Create Date: 2026-06-14 17:06:46.172353

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8d56f94fed2e"
down_revision: str | None = "9a81552f7f7e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "document_analyses",
        sa.Column(
            "processing_stage", sa.String(length=50), nullable=False, server_default="pending"
        ),
    )
    op.add_column(
        "document_analyses",
        sa.Column("processing_step", sa.Integer(), nullable=False, server_default="0"),
    )
    op.create_index(
        op.f("ix_document_analyses_processing_stage"),
        "document_analyses",
        ["processing_stage"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_document_analyses_processing_stage"), table_name="document_analyses")
    op.drop_column("document_analyses", "processing_step")
    op.drop_column("document_analyses", "processing_stage")
    # ### end Alembic commands ###
