from __future__ import annotations

import argparse
import os
import random
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

DEFAULT_OUT_DIR = "storage/classifier_training"
DEFAULT_TRAIN_PER_CLASS = 200
DEFAULT_VALID_PER_CLASS = 60

_CLASS_TEMPLATES: dict[str, dict[str, list[str]]] = {
    "invoices": {
        "headers": [
            "INVOICE",
            "FAKTURA VAT",
            "Tax Invoice",
            "Faktura nr",
            "Bill To",
            "Ship To",
            "Sprzedawca",
            "Nabywca",
            "Invoice Number",
            "Numer faktury",
            "Issue date",
            "Data wystawienia",
            "Due date",
            "Termin płatności",
            "Payment terms",
            "Sposób płatności",
        ],
        "vocab": [
            "invoice",
            "faktura",
            "VAT",
            "NIP",
            "REGON",
            "subtotal",
            "total",
            "amount",
            "kwota",
            "netto",
            "brutto",
            "tax",
            "podatek",
            "discount",
            "rabat",
            "quantity",
            "ilość",
            "unit",
            "jednostka",
            "price",
            "cena",
            "remit",
            "paid",
            "zapłacono",
            "outstanding",
            "balance",
            "saldo",
            "purchase order",
            "PO",
            "zamówienie",
            "delivery",
            "dostawa",
            "service",
            "usługa",
            "product",
            "produkt",
            "line item",
            "pozycja",
            "EUR",
            "PLN",
            "USD",
            "GBP",
            "currency",
            "waluta",
            "IBAN",
            "SWIFT",
            "bank account",
            "rachunek bankowy",
        ],
        "phrases": [
            "Total amount due: 1,250.00 EUR",
            "Subtotal: 1,016.26 net VAT 23% 233.74",
            "Please remit payment within 14 days of invoice date.",
            "Bank transfer to IBAN PL61 1090 1014 0000 0712 1981 2874",
            "Goods sold and delivered as per purchase order #PO-2024-0331",
            "Faktura VAT nr FV/2024/03/118 wystawiona dnia 15.03.2024",
            "Sprzedawca: ACME Sp. z o.o., ul. Polna 12, 00-001 Warszawa, NIP 525-000-00-00",
            "Nabywca: Klient Końcowy S.A., NIP 1234567890",
            "Pozycja 1: Usługa konsultingowa, ilość 10 godzin, cena netto 150.00 PLN",
            "Razem netto 1500.00 PLN, VAT 23% 345.00 PLN, brutto 1845.00 PLN",
            "Sposób płatności: przelew, termin 14 dni",
            "Numer rachunku bankowego do wpłaty: 12 3456 7890 1234 5678 9012 3456",
        ],
    },
    "contracts": {
        "headers": [
            "AGREEMENT",
            "CONTRACT",
            "UMOWA",
            "Service Agreement",
            "Non-Disclosure Agreement",
            "Umowa o zachowaniu poufności",
            "WHEREAS",
            "NOW THEREFORE",
            "Article",
            "Artykuł",
            "Section",
            "Paragraf",
            "Recitals",
            "Preambuła",
            "Definitions",
            "Definicje",
            "Signatures",
            "Podpisy",
        ],
        "vocab": [
            "agreement",
            "umowa",
            "party",
            "strona",
            "contractor",
            "wykonawca",
            "client",
            "zleceniodawca",
            "obligation",
            "obowiązek",
            "right",
            "prawo",
            "term",
            "okres",
            "termination",
            "rozwiązanie",
            "confidential",
            "poufny",
            "intellectual property",
            "własność intelektualna",
            "warranty",
            "gwarancja",
            "indemnity",
            "odszkodowanie",
            "liability",
            "odpowiedzialność",
            "force majeure",
            "siła wyższa",
            "governing law",
            "jurysdykcja",
            "dispute",
            "spór",
            "amendment",
            "zmiana",
            "annex",
            "załącznik",
            "consideration",
            "wynagrodzenie",
            "scope",
            "zakres",
            "deliverables",
            "rezultaty",
            "milestone",
            "etap",
            "acceptance",
            "odbiór",
        ],
        "phrases": [
            "This Agreement is entered into as of the Effective Date by and between the Parties.",
            "Each Party shall keep Confidential Information of the other Party in strict confidence.",
            "The term of this Agreement shall commence on the Effective Date and continue for twelve (12) months.",
            "Either Party may terminate this Agreement upon thirty (30) days written notice.",
            "Niniejsza umowa zostaje zawarta w dniu 15 marca 2024 roku w Warszawie pomiędzy:",
            "Zleceniodawca zobowiązuje się do zapłaty wynagrodzenia w wysokości 50 000 PLN netto.",
            "Wykonawca oświadcza, że posiada wszelkie uprawnienia i kwalifikacje niezbędne do realizacji przedmiotu Umowy.",
            "Wszelkie zmiany niniejszej Umowy wymagają formy pisemnej pod rygorem nieważności.",
            "W sprawach nieuregulowanych niniejszą Umową zastosowanie mają przepisy Kodeksu cywilnego.",
            "Spory wynikające z Umowy będą rozstrzygane przez sąd właściwy dla siedziby Zleceniodawcy.",
            "Strony oświadczają, że zapoznały się z treścią Umowy i akceptują jej postanowienia bez zastrzeżeń.",
            "Załącznik nr 1 stanowi integralną część niniejszej Umowy.",
        ],
    },
    "id_card": {
        "headers": [
            "IDENTITY CARD",
            "DOWÓD OSOBISTY",
            "Personal Identity Document",
            "REPUBLIC OF POLAND",
            "RZECZPOSPOLITA POLSKA",
            "ID",
        ],
        "vocab": [
            "identity",
            "dowód",
            "tożsamość",
            "PESEL",
            "surname",
            "nazwisko",
            "given names",
            "imiona",
            "date of birth",
            "data urodzenia",
            "place of birth",
            "miejsce urodzenia",
            "nationality",
            "obywatelstwo",
            "sex",
            "płeć",
            "date of issue",
            "data wydania",
            "date of expiry",
            "data ważności",
            "issuing authority",
            "organ wydający",
            "document number",
            "numer dokumentu",
            "MRZ",
            "Polish",
            "polskie",
            "Citizenship",
            "M",
            "F",
            "K",
        ],
        "phrases": [
            "RZECZPOSPOLITA POLSKA / REPUBLIC OF POLAND",
            "Nazwisko / Surname: KOWALSKI",
            "Imiona / Given names: JAN ANDRZEJ",
            "Obywatelstwo / Nationality: POL",
            "Data urodzenia / Date of birth: 27.01.1985",
            "Miejsce urodzenia / Place of birth: KRAKÓW",
            "Płeć / Sex: M",
            "Numer PESEL: 85012712345",
            "Numer dowodu osobistego: ABC123456",
            "Data ważności / Date of expiry: 15.03.2034",
            "Data wydania / Date of issue: 15.03.2024",
            "Organ wydający / Issuing authority: PREZYDENT M.ST. WARSZAWY",
            "IDPOL<<KOWALSKI<<JAN<<ANDRZEJ<<<<<<<<<<<<<<<",
            "8501271234<5POL8501271M3403158<<<<<<<<<<<<<<06",
        ],
    },
    "passport": {
        "headers": [
            "PASSPORT",
            "PASZPORT",
            "REPUBLIC OF POLAND",
            "RZECZPOSPOLITA POLSKA",
            "Type",
            "Typ",
            "Country code",
            "Kod kraju",
        ],
        "vocab": [
            "passport",
            "paszport",
            "biometric",
            "biometryczny",
            "P",
            "surname",
            "nazwisko",
            "given names",
            "imiona",
            "nationality",
            "obywatelstwo",
            "POL",
            "POLISH",
            "date of birth",
            "data urodzenia",
            "sex",
            "płeć",
            "place of birth",
            "miejsce urodzenia",
            "date of issue",
            "data wydania",
            "date of expiry",
            "data ważności",
            "authority",
            "organ",
            "passport number",
            "numer paszportu",
            "MRZ",
            "machine readable zone",
            "holder",
            "okaziciel",
        ],
        "phrases": [
            "PASSPORT / PASZPORT",
            "Type / Typ: P",
            "Country code / Kod państwa: POL",
            "Passport No. / Nr paszportu: EA1234567",
            "Surname / Nazwisko: NOWAK",
            "Given names / Imiona: ANNA MARIA",
            "Nationality / Obywatelstwo: POLISH / POLSKIE",
            "Date of birth / Data urodzenia: 12 MAR 1990",
            "Sex / Płeć: F",
            "Place of birth / Miejsce urodzenia: WARSZAWA",
            "Date of issue / Data wydania: 04 JUN 2022",
            "Date of expiry / Data ważności: 03 JUN 2032",
            "Authority / Organ wydający: WOJEWODA MAZOWIECKI",
            "P<POLNOWAK<<ANNA<MARIA<<<<<<<<<<<<<<<<<<<<<<<<",
            "EA1234567<7POL9003122F3206035<<<<<<<<<<<<<<04",
            "This passport contains 32 pages. Holder's signature appears on the data page.",
        ],
    },
    "bank_statements": {
        "headers": [
            "BANK STATEMENT",
            "WYCIĄG BANKOWY",
            "Account Statement",
            "Wyciąg z rachunku",
            "Opening balance",
            "Saldo początkowe",
            "Closing balance",
            "Saldo końcowe",
            "Transactions",
            "Operacje",
            "Statement period",
            "Okres rozliczeniowy",
        ],
        "vocab": [
            "account",
            "rachunek",
            "balance",
            "saldo",
            "deposit",
            "wpłata",
            "withdrawal",
            "wypłata",
            "transaction",
            "transakcja",
            "transfer",
            "przelew",
            "IBAN",
            "BIC",
            "SWIFT",
            "credit",
            "uznanie",
            "debit",
            "obciążenie",
            "interest",
            "odsetki",
            "fee",
            "opłata",
            "available balance",
            "saldo dostępne",
            "currency",
            "waluta",
            "PLN",
            "EUR",
            "USD",
            "card transaction",
            "płatność kartą",
            "ATM",
            "bankomat",
            "salary",
            "wynagrodzenie",
            "merchant",
            "akceptant",
        ],
        "phrases": [
            "Account number: PL61 1090 1014 0000 0712 1981 2874",
            "Statement period: 01.03.2024 - 31.03.2024",
            "Opening balance: 12,450.00 PLN",
            "Closing balance: 14,832.17 PLN",
            "Transaction 05.03.2024 Salary PAYROLL +5,000.00 PLN",
            "Transaction 07.03.2024 Card payment BIEDRONKA 24/07 -124.36 PLN",
            "Transaction 10.03.2024 ATM withdrawal Warsaw -500.00 PLN",
            "Transaction 15.03.2024 Transfer to PL12 3456 ... -1,500.00 PLN",
            "Transaction 20.03.2024 Direct debit ENERGA -218.75 PLN",
            "Transaction 31.03.2024 Interest credit +1.23 PLN",
            "Wyciąg z rachunku osobistego za okres 01.03.2024 - 31.03.2024",
            "Saldo początkowe: 12 450,00 PLN, Saldo końcowe: 14 832,17 PLN",
            "Liczba operacji: 17, Obciążenia: 5 312,11 PLN, Uznania: 7 694,28 PLN",
            "Bank: PKO Bank Polski S.A., Oddział: Warszawa Centrum",
        ],
    },
    "tax_forms": {
        "headers": [
            "TAX RETURN",
            "Tax Return Form",
            "DEKLARACJA PODATKOWA",
            "PIT-37",
            "PIT-36",
            "PIT-11",
            "VAT-7",
            "CIT-8",
            "Form 1040",
            "W-2",
            "Schedule A",
            "Taxpayer",
            "Podatnik",
            "Tax year",
            "Rok podatkowy",
            "Filing status",
            "Status rozliczeniowy",
        ],
        "vocab": [
            "tax",
            "podatek",
            "income",
            "dochód",
            "deduction",
            "odliczenie",
            "exemption",
            "ulga",
            "refund",
            "zwrot",
            "withholding",
            "zaliczka",
            "taxpayer",
            "podatnik",
            "spouse",
            "małżonek",
            "dependent",
            "osoba na utrzymaniu",
            "filing",
            "rozliczenie",
            "schedule",
            "załącznik",
            "PIT",
            "VAT",
            "CIT",
            "IRS",
            "Urząd Skarbowy",
            "social security",
            "ZUS",
            "health insurance",
            "ubezpieczenie zdrowotne",
            "gross income",
            "przychód brutto",
            "net income",
            "dochód netto",
            "tax due",
            "podatek należny",
            "tax base",
            "podstawa opodatkowania",
        ],
        "phrases": [
            "Form 1040 U.S. Individual Income Tax Return for tax year 2023",
            "Filing Status: Married filing jointly",
            "Wages, salaries, tips (Form W-2 box 1): 78,250.00",
            "Federal income tax withheld: 9,830.00",
            "Earned income tax credit (EIC): 0.00",
            "Total tax: 8,412.00, Refund amount: 1,418.00",
            "PIT-37 Zeznanie o wysokości osiągniętego dochodu w roku podatkowym 2023",
            "Dane podatnika: KOWALSKI JAN, PESEL 85012712345, NIP 1234567890",
            "Urząd Skarbowy właściwy: Pierwszy Urząd Skarbowy Warszawa-Śródmieście",
            "Suma przychodów ze stosunku pracy: 96 000,00 PLN",
            "Koszty uzyskania przychodu: 3 000,00 PLN",
            "Składki na ubezpieczenia społeczne: 13 162,00 PLN",
            "Podstawa obliczenia podatku po odliczeniach: 79 838,00 PLN",
            "Podatek należny: 9 580,00 PLN, Zaliczka pobrana: 11 200,00 PLN",
            "Kwota do zwrotu: 1 620,00 PLN",
            "Oświadczam, że dane wykazane w deklaracji są zgodne ze stanem faktycznym.",
        ],
    },
}


def _generate_sample(rng: random.Random, templates: dict[str, list[str]]) -> str:
    headers = rng.sample(templates["headers"], k=min(3, len(templates["headers"])))
    vocab = rng.sample(templates["vocab"], k=min(rng.randint(25, 45), len(templates["vocab"])))
    n_phrases = min(rng.randint(6, len(templates["phrases"])), len(templates["phrases"]))
    phrases = rng.sample(templates["phrases"], k=n_phrases)

    parts: list[str] = []
    parts.append(" ".join(headers).upper())
    parts.append(" ".join(phrases))
    parts.append(" ".join(vocab))
    if rng.random() < 0.5:
        parts.append(" ".join(rng.sample(vocab, k=min(10, len(vocab)))))
    rng.shuffle(parts)
    return "  ".join(parts)


def generate_split(out_dir: str, split_name: str, samples_per_class: int, seed: int) -> None:
    rng = random.Random(seed)
    for class_name, templates in _CLASS_TEMPLATES.items():
        class_dir = os.path.join(out_dir, split_name, class_name)
        os.makedirs(class_dir, exist_ok=True)
        for i in range(samples_per_class):
            text = _generate_sample(rng, templates)
            file_path = os.path.join(class_dir, f"synthetic_{i:04d}.txt")
            with open(file_path, "w", encoding="utf-8") as f:
                f.write(text)
        print(f"  {split_name}/{class_name}: generated {samples_per_class} samples")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate synthetic training data.")
    parser.add_argument("--out-dir", default=DEFAULT_OUT_DIR)
    parser.add_argument("--train", type=int, default=DEFAULT_TRAIN_PER_CLASS)
    parser.add_argument("--valid", type=int, default=DEFAULT_VALID_PER_CLASS)
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()

    print("=" * 50)
    print(" SYNTHETIC TRAINING DATA GENERATOR")
    print("=" * 50)
    print(f" Output:  {args.out_dir}")
    print(f" Classes: {', '.join(_CLASS_TEMPLATES.keys())}")
    print(f" Train:   {args.train} samples/class")
    print(f" Valid:   {args.valid} samples/class")

    generate_split(args.out_dir, "train", args.train, args.seed)
    generate_split(args.out_dir, "valid", args.valid, args.seed + 1000)

    print("\n[OK] Done. Now run: python scripts/train_classifier.py")
