from __future__ import annotations

import argparse
import os
import random
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

DEFAULT_OUT_DIR = "storage/classifier_training"
DEFAULT_TRAIN_PER_CLASS = 200
DEFAULT_VALID_PER_CLASS = 60

_CLASS_TEMPLATES: dict[str, dict[str, list[str]]] = {
    "invoices": {
        "headers": [
            "INVOICE",
            "FAKTURA VAT",
            "Tax Invoice",
            "Faktura nr",
            "Bill To",
            "Ship To",
            "Sprzedawca",
            "Nabywca",
            "Invoice Number",
            "Numer faktury",
            "Issue date",
            "Data wystawienia",
            "Due date",
            "Termin płatności",
            "Payment terms",
            "Sposób płatności",
        ],
        "vocab": [
            "invoice",
            "faktura",
            "VAT",
            "NIP",
            "REGON",
            "subtotal",
            "total",
            "amount",
            "kwota",
            "netto",
            "brutto",
            "tax",
            "podatek",
            "discount",
            "rabat",
            "quantity",
            "ilość",
            "unit",
            "jednostka",
            "price",
            "cena",
            "remit",
            "paid",
            "zapłacono",
            "outstanding",
            "balance",
            "saldo",
            "purchase order",
            "PO",
            "zamówienie",
            "delivery",
            "dostawa",
            "service",
            "usługa",
            "product",
            "produkt",
            "line item",
            "pozycja",
            "EUR",
            "PLN",
            "USD",
            "GBP",
            "currency",
            "waluta",
            "IBAN",
            "SWIFT",
            "bank account",
            "rachunek bankowy",
        ],
        "phrases": [
            "Total amount due: 1,250.00 EUR",
            "Subtotal: 1,016.26 net VAT 23% 233.74",
            "Please remit payment within 14 days of invoice date.",
            "Bank transfer to IBAN PL61 1090 1014 0000 0712 1981 2874",
            "Goods sold and delivered as per purchase order #PO-2024-0331",
            "Faktura VAT nr FV/2024/03/118 wystawiona dnia 15.03.2024",
            "Sprzedawca: ACME Sp. z o.o., ul. Polna 12, 00-001 Warszawa, NIP 525-000-00-00",
            "Nabywca: Klient Końcowy S.A., NIP 1234567890",
            "Pozycja 1: Usługa konsultingowa, ilość 10 godzin, cena netto 150.00 PLN",
            "Razem netto 1500.00 PLN, VAT 23% 345.00 PLN, brutto 1845.00 PLN",
            "Sposób płatności: przelew, termin 14 dni",
            "Numer rachunku bankowego do wpłaty: 12 3456 7890 1234 5678 9012 3456",
        ],
    },
    "contracts": {
        "headers": [
            "AGREEMENT",
            "CONTRACT",
            "UMOWA",
            "UMOWA O SWIADCZENIE USLUG",
            "UMOWA O ŚWIADCZENIE USŁUG",
            "UMOWA ZLECENIE",
            "UMOWA O DZIEŁO",
            "Service Agreement",
            "Non-Disclosure Agreement",
            "Umowa o zachowaniu poufności",
            "WHEREAS",
            "NOW THEREFORE",
            "Article",
            "Artykuł",
            "Section",
            "Paragraf",
            "Recitals",
            "Preambuła",
            "Definitions",
            "Definicje",
            "Signatures",
            "Podpisy",
            "Strony umowy",
            "Przedmiot umowy",
        ],
        "vocab": [
            "agreement",
            "umowa",
            "party",
            "strona",
            "strony",
            "contractor",
            "wykonawca",
            "client",
            "zleceniodawca",
            "zamawiajacy",
            "zamawiający",
            "swiadczenie",
            "świadczenie",
            "uslug",
            "usług",
            "usluga",
            "usługa",
            "obligation",
            "obowiązek",
            "right",
            "prawo",
            "term",
            "okres",
            "termination",
            "rozwiązanie",
            "confidential",
            "poufny",
            "intellectual property",
            "własność intelektualna",
            "warranty",
            "gwarancja",
            "indemnity",
            "odszkodowanie",
            "liability",
            "odpowiedzialność",
            "force majeure",
            "siła wyższa",
            "governing law",
            "jurysdykcja",
            "dispute",
            "spór",
            "amendment",
            "zmiana",
            "annex",
            "załącznik",
            "zalacznik",
            "consideration",
            "wynagrodzenie",
            "ryczalt",
            "ryczałt",
            "ryczaltowe",
            "ryczałtowe",
            "netto",
            "scope",
            "zakres",
            "deliverables",
            "rezultaty",
            "milestone",
            "etap",
            "acceptance",
            "odbiór",
            "przedmiot",
            "realizacja",
        ],
        "phrases": [
            "This Agreement is entered into as of the Effective Date by and between the Parties.",
            "Each Party shall keep Confidential Information of the other Party in strict confidence.",
            "The term of this Agreement shall commence on the Effective Date and continue for twelve (12) months.",
            "Either Party may terminate this Agreement upon thirty (30) days written notice.",
            "UMOWA O SWIADCZENIE USLUG zawarta w Warszawie dnia 15.03.2024 pomiedzy stronami:",
            "Zamawiajacy: ABC sp. z o.o., ul. Testowa 1, 00-001 Warszawa.",
            "Wykonawca: Jan Kowalski, ul. Przykladowa 2, 30-001 Krakow.",
            "Przedmiotem umowy jest wykonanie uslugi informatycznej polegajacej na wdrozeniu systemu.",
            "Strony ustalaja wynagrodzenie ryczaltowe w wysokosci 5000 PLN netto.",
            "Zalacznik nr 1 stanowi integralna czesc niniejszej Umowy.",
            "Niniejsza umowa zostaje zawarta w dniu 15 marca 2024 roku w Warszawie pomiędzy:",
            "Zleceniodawca zobowiązuje się do zapłaty wynagrodzenia w wysokości 50 000 PLN netto.",
            "Wykonawca oświadcza, że posiada wszelkie uprawnienia i kwalifikacje niezbędne do realizacji przedmiotu Umowy.",
            "Wszelkie zmiany niniejszej Umowy wymagają formy pisemnej pod rygorem nieważności.",
            "W sprawach nieuregulowanych niniejszą Umową zastosowanie mają przepisy Kodeksu cywilnego.",
            "Spory wynikające z Umowy będą rozstrzygane przez sąd właściwy dla siedziby Zleceniodawcy.",
            "Strony oświadczają, że zapoznały się z treścią Umowy i akceptują jej postanowienia bez zastrzeżeń.",
            "Załącznik nr 1 stanowi integralną część niniejszej Umowy.",
        ],
    },
    "id_card": {
        "headers": [
            "IDENTITY CARD",
            "DOWÓD OSOBISTY",
            "Personal Identity Document",
            "REPUBLIC OF POLAND",
            "RZECZPOSPOLITA POLSKA",
            "ID",
        ],
        "vocab": [
            "identity",
            "dowód",
            "tożsamość",
            "PESEL",
            "surname",
            "nazwisko",
            "given names",
            "imiona",
            "date of birth",
            "data urodzenia",
            "place of birth",
            "miejsce urodzenia",
            "nationality",
            "obywatelstwo",
            "sex",
            "płeć",
            "date of issue",
            "data wydania",
            "date of expiry",
            "data ważności",
            "issuing authority",
            "organ wydający",
            "document number",
            "numer dokumentu",
            "MRZ",
            "Polish",
            "polskie",
            "Citizenship",
            "M",
            "F",
            "K",
        ],
        "phrases": [
            "RZECZPOSPOLITA POLSKA / REPUBLIC OF POLAND",
            "Nazwisko / Surname: KOWALSKI",
            "Imiona / Given names: JAN ANDRZEJ",
            "Obywatelstwo / Nationality: POL",
            "Data urodzenia / Date of birth: 27.01.1985",
            "Miejsce urodzenia / Place of birth: KRAKÓW",
            "Płeć / Sex: M",
            "Numer PESEL: 85012712345",
            "Numer dowodu osobistego: ABC123456",
            "Data ważności / Date of expiry: 15.03.2034",
            "Data wydania / Date of issue: 15.03.2024",
            "Organ wydający / Issuing authority: PREZYDENT M.ST. WARSZAWY",
            "IDPOL<<KOWALSKI<<JAN<<ANDRZEJ<<<<<<<<<<<<<<<",
            "8501271234<5POL8501271M3403158<<<<<<<<<<<<<<06",
        ],
    },
    "passport": {
        "headers": [
            "PASSPORT",
            "PASZPORT",
            "REPUBLIC OF POLAND",
            "RZECZPOSPOLITA POLSKA",
            "Type",
            "Typ",
            "Country code",
            "Kod kraju",
        ],
        "vocab": [
            "passport",
            "paszport",
            "biometric",
            "biometryczny",
            "P",
            "surname",
            "nazwisko",
            "given names",
            "imiona",
            "nationality",
            "obywatelstwo",
            "POL",
            "POLISH",
            "date of birth",
            "data urodzenia",
            "sex",
            "płeć",
            "place of birth",
            "miejsce urodzenia",
            "date of issue",
            "data wydania",
            "date of expiry",
            "data ważności",
            "authority",
            "organ",
            "passport number",
            "numer paszportu",
            "MRZ",
            "machine readable zone",
            "holder",
            "okaziciel",
        ],
        "phrases": [
            "PASSPORT / PASZPORT",
            "Type / Typ: P",
            "Country code / Kod państwa: POL",
            "Passport No. / Nr paszportu: EA1234567",
            "Surname / Nazwisko: NOWAK",
            "Given names / Imiona: ANNA MARIA",
            "Nationality / Obywatelstwo: POLISH / POLSKIE",
            "Date of birth / Data urodzenia: 12 MAR 1990",
            "Sex / Płeć: F",
            "Place of birth / Miejsce urodzenia: WARSZAWA",
            "Date of issue / Data wydania: 04 JUN 2022",
            "Date of expiry / Data ważności: 03 JUN 2032",
            "Authority / Organ wydający: WOJEWODA MAZOWIECKI",
            "P<POLNOWAK<<ANNA<MARIA<<<<<<<<<<<<<<<<<<<<<<<<",
            "EA1234567<7POL9003122F3206035<<<<<<<<<<<<<<04",
            "This passport contains 32 pages. Holder's signature appears on the data page.",
        ],
    },
    "bank_statements": {
        "headers": [
            "BANK STATEMENT",
            "WYCIĄG BANKOWY",
            "Account Statement",
            "Wyciąg z rachunku",
            "Opening balance",
            "Saldo początkowe",
            "Closing balance",
            "Saldo końcowe",
            "Transactions",
            "Operacje",
            "Statement period",
            "Okres rozliczeniowy",
        ],
        "vocab": [
            "account",
            "rachunek",
            "balance",
            "saldo",
            "deposit",
            "wpłata",
            "withdrawal",
            "wypłata",
            "transaction",
            "transakcja",
            "transfer",
            "przelew",
            "IBAN",
            "BIC",
            "SWIFT",
            "credit",
            "uznanie",
            "debit",
            "obciążenie",
            "interest",
            "odsetki",
            "fee",
            "opłata",
            "available balance",
            "saldo dostępne",
            "currency",
            "waluta",
            "PLN",
            "EUR",
            "USD",
            "card transaction",
            "płatność kartą",
            "ATM",
            "bankomat",
            "salary",
            "wynagrodzenie",
            "merchant",
            "akceptant",
        ],
        "phrases": [
            "Account number: PL61 1090 1014 0000 0712 1981 2874",
            "Statement period: 01.03.2024 - 31.03.2024",
            "Opening balance: 12,450.00 PLN",
            "Closing balance: 14,832.17 PLN",
            "Transaction 05.03.2024 Salary PAYROLL +5,000.00 PLN",
            "Transaction 07.03.2024 Card payment BIEDRONKA 24/07 -124.36 PLN",
            "Transaction 10.03.2024 ATM withdrawal Warsaw -500.00 PLN",
            "Transaction 15.03.2024 Transfer to PL12 3456 ... -1,500.00 PLN",
            "Transaction 20.03.2024 Direct debit ENERGA -218.75 PLN",
            "Transaction 31.03.2024 Interest credit +1.23 PLN",
            "Wyciąg z rachunku osobistego za okres 01.03.2024 - 31.03.2024",
            "Saldo początkowe: 12 450,00 PLN, Saldo końcowe: 14 832,17 PLN",
            "Liczba operacji: 17, Obciążenia: 5 312,11 PLN, Uznania: 7 694,28 PLN",
            "Bank: PKO Bank Polski S.A., Oddział: Warszawa Centrum",
        ],
    },
    "tax_forms": {
        "headers": [
            "TAX RETURN",
            "Tax Return Form",
            "DEKLARACJA PODATKOWA",
            "PIT-37",
            "PIT-36",
            "PIT-11",
            "VAT-7",
            "CIT-8",
            "Form 1040",
            "W-2",
            "Schedule A",
            "Taxpayer",
            "Podatnik",
            "Tax year",
            "Rok podatkowy",
            "Filing status",
            "Status rozliczeniowy",
        ],
        "vocab": [
            "tax",
            "podatek",
            "income",
            "dochód",
            "deduction",
            "odliczenie",
            "exemption",
            "ulga",
            "refund",
            "zwrot",
            "withholding",
            "zaliczka",
            "taxpayer",
            "podatnik",
            "spouse",
            "małżonek",
            "dependent",
            "osoba na utrzymaniu",
            "filing",
            "rozliczenie",
            "schedule",
            "załącznik",
            "PIT",
            "VAT",
            "CIT",
            "IRS",
            "Urząd Skarbowy",
            "social security",
            "ZUS",
            "health insurance",
            "ubezpieczenie zdrowotne",
            "gross income",
            "przychód brutto",
            "net income",
            "dochód netto",
            "tax due",
            "podatek należny",
            "tax base",
            "podstawa opodatkowania",
        ],
        "phrases": [
            "Form 1040 U.S. Individual Income Tax Return for tax year 2023",
            "Filing Status: Married filing jointly",
            "Wages, salaries, tips (Form W-2 box 1): 78,250.00",
            "Federal income tax withheld: 9,830.00",
            "Earned income tax credit (EIC): 0.00",
            "Total tax: 8,412.00, Refund amount: 1,418.00",
            "PIT-37 Zeznanie o wysokości osiągniętego dochodu w roku podatkowym 2023",
            "Dane podatnika: KOWALSKI JAN, PESEL 85012712345, NIP 1234567890",
            "Urząd Skarbowy właściwy: Pierwszy Urząd Skarbowy Warszawa-Śródmieście",
            "Suma przychodów ze stosunku pracy: 96 000,00 PLN",
            "Koszty uzyskania przychodu: 3 000,00 PLN",
            "Składki na ubezpieczenia społeczne: 13 162,00 PLN",
            "Podstawa obliczenia podatku po odliczeniach: 79 838,00 PLN",
            "Podatek należny: 9 580,00 PLN, Zaliczka pobrana: 11 200,00 PLN",
            "Kwota do zwrotu: 1 620,00 PLN",
            "Oświadczam, że dane wykazane w deklaracji są zgodne ze stanem faktycznym.",
        ],
    },
    "financial_reports": {
        "headers": [
            "ANNUAL REPORT",
            "FINANCIAL REPORT",
            "RAPORT ROCZNY",
            "SPRAWOZDANIE FINANSOWE",
            "Balance Sheet",
            "Bilans",
            "Income Statement",
            "Rachunek zysków i strat",
            "Cash Flow Statement",
            "Rachunek przepływów pieniężnych",
            "Consolidated Financial Statements",
            "Skonsolidowane sprawozdanie finansowe",
            "Notes to Financial Statements",
            "Informacja dodatkowa",
        ],
        "vocab": [
            "revenue",
            "przychody",
            "profit",
            "zysk",
            "loss",
            "strata",
            "assets",
            "aktywa",
            "liabilities",
            "pasywa",
            "equity",
            "kapitał własny",
            "earnings per share",
            "zysk na akcję",
            "EBITDA",
            "operating income",
            "wynik operacyjny",
            "net income",
            "zysk netto",
            "dividend",
            "dywidenda",
            "shareholders",
            "akcjonariusze",
            "auditor",
            "biegły rewident",
            "consolidated",
            "skonsolidowany",
            "subsidiary",
            "spółka zależna",
            "fiscal year",
            "rok obrotowy",
            "depreciation",
            "amortyzacja",
            "goodwill",
            "wartość firmy",
            "inventory",
            "zapasy",
            "receivables",
            "należności",
            "provisions",
            "rezerwy",
        ],
        "phrases": [
            "Annual Report 2023 — Consolidated Financial Statements",
            "Total revenue for the year ended 31 December 2023: PLN 1,245,000 thousand",
            "Net profit attributable to shareholders: PLN 87,432 thousand",
            "Earnings per share (basic): PLN 4.37",
            "Total assets: PLN 3,812,000 thousand, Total liabilities: PLN 2,101,000 thousand",
            "Dividend per share declared: PLN 2.00",
            "The Board of Directors presents the Annual Report for the fiscal year 2023.",
            "Sprawozdanie finansowe za rok obrotowy zakończony 31 grudnia 2023 r.",
            "Przychody ze sprzedaży: 1 245 000 tys. PLN (wzrost o 12% r/r)",
            "Zysk netto: 87 432 tys. PLN, EBITDA: 198 760 tys. PLN",
            "Kapitał własny: 1 711 000 tys. PLN, Zobowiązania długoterminowe: 842 000 tys. PLN",
            "Biegły rewident wydał opinię bez zastrzeżeń do sprawozdania finansowego.",
            "Operating cash flow: PLN 156,234 thousand; Investing activities: PLN -89,000 thousand",
            "Goodwill recognised on acquisition of subsidiary: PLN 45,000 thousand",
        ],
    },
    "government_tenders": {
        "headers": [
            "INVITATION TO TENDER",
            "REQUEST FOR PROPOSAL",
            "ZAPYTANIE OFERTOWE",
            "SPECYFIKACJA WARUNKÓW ZAMÓWIENIA",
            "SWZ",
            "OGŁOSZENIE O ZAMÓWIENIU",
            "PUBLIC PROCUREMENT",
            "ZAMÓWIENIE PUBLICZNE",
            "PRZETARG NIEOGRANICZONY",
            "Open Tender",
            "Contracting Authority",
            "Zamawiający",
        ],
        "vocab": [
            "tender",
            "przetarg",
            "procurement",
            "zamówienie",
            "bid",
            "oferta",
            "bidder",
            "oferent",
            "contracting authority",
            "zamawiający",
            "specification",
            "specyfikacja",
            "evaluation criteria",
            "kryteria oceny",
            "submission deadline",
            "termin składania ofert",
            "contract value",
            "wartość zamówienia",
            "CPV",
            "lot",
            "część zamówienia",
            "framework agreement",
            "umowa ramowa",
            "OJEU",
            "Dziennik Urzędowy UE",
            "award",
            "udzielenie zamówienia",
            "rejection",
            "odrzucenie oferty",
            "security deposit",
            "wadium",
            "performance bond",
            "zabezpieczenie należytego wykonania",
            "public law",
            "prawo zamówień publicznych",
            "PZP",
        ],
        "phrases": [
            "Invitation to Tender No. ZP/2024/03/07 for the supply of IT equipment",
            "Contracting Authority: City of Warsaw, Pl. Bankowy 3/5, 00-950 Warsaw",
            "Estimated contract value (net): EUR 250,000 (above EU threshold)",
            "Submission deadline: 15 April 2024, 12:00 CET",
            "Evaluation criteria: Price 60%, Technical quality 40%",
            "Security deposit (wadium): PLN 5,000, valid for 30 days from submission deadline",
            "Ogłoszenie o zamówieniu nr ZP/2024/03/07 — dostawa sprzętu informatycznego",
            "Zamawiający: Miasto Stołeczne Warszawa, pl. Bankowy 3/5, 00-950 Warszawa, NIP 525-22-48-481",
            "Szacunkowa wartość zamówienia (netto): 1 075 000,00 PLN (powyżej progu UE)",
            "Termin składania ofert: 15 kwietnia 2024 r., godz. 12:00",
            "Kryteria oceny ofert: Cena 60%, Termin realizacji 20%, Okres gwarancji 20%",
            "Wadium: 5 000,00 PLN, okres związania ofertą: 30 dni",
            "Wykonawca musi spełniać warunki udziału w postępowaniu określone w SWZ.",
            "CPV: 30213100-6 Komputery przenośne, 30232110-8 Drukarki laserowe",
        ],
    },
    "laws_and_regulations": {
        "headers": [
            "ACT",
            "REGULATION",
            "USTAWA",
            "ROZPORZĄDZENIE",
            "DIRECTIVE",
            "DYREKTYWA",
            "ORDINANCE",
            "ZARZĄDZENIE",
            "DECREE",
            "DEKRET",
            "Journal of Laws",
            "Dziennik Ustaw",
            "Official Journal",
            "Dziennik Urzędowy",
            "Parliament",
            "Sejm",
        ],
        "vocab": [
            "act",
            "ustawa",
            "regulation",
            "rozporządzenie",
            "article",
            "artykuł",
            "section",
            "paragraf",
            "clause",
            "ustęp",
            "provision",
            "przepis",
            "amendment",
            "nowelizacja",
            "repeal",
            "uchylenie",
            "enforcement",
            "wejście w życie",
            "penalty",
            "kara",
            "fine",
            "grzywna",
            "obligation",
            "obowiązek",
            "prohibition",
            "zakaz",
            "minister",
            "sejm",
            "senat",
            "president",
            "president",
            "entry into force",
            "vacatio legis",
            "implementing measure",
            "środek wykonawczy",
            "statutory",
            "ustawowy",
            "legislative",
            "ustawodawczy",
        ],
        "phrases": [
            "ACT of 11 March 2004 on the Tax on Goods and Services (VAT Act)",
            "Article 1. This Act regulates the taxation of goods and services.",
            "Article 5(1). The following activities shall be subject to taxation: supply of goods.",
            "Article 86. The taxpayer shall have the right to deduct input tax.",
            "The Act shall enter into force 14 days after the date of its publication.",
            "Ustawa z dnia 11 marca 2004 r. o podatku od towarów i usług (Dz.U. z 2024 r. poz. 361)",
            "Art. 1. Ustawa reguluje opodatkowanie podatkiem od towarów i usług.",
            "Art. 5 ust. 1. Opodatkowaniu podatkiem podlegają: odpłatna dostawa towarów.",
            "Art. 86. Podatnikowi przysługuje prawo do obniżenia kwoty podatku należnego.",
            "Ustawa wchodzi w życie po upływie 14 dni od dnia ogłoszenia.",
            "Rozporządzenie Ministra Finansów z dnia 3 grudnia 2013 r. w sprawie wystawiania faktur",
            "§ 3. Faktury wystawia się nie wcześniej niż 30. dnia przed dokonaniem dostawy towarów.",
            "Na podstawie art. 14a ust. 3 ustawy z dnia 11 marca 2004 r. zarządza się, co następuje:",
            "Przepisy niniejszego rozporządzenia stosuje się od dnia 1 stycznia 2025 r.",
        ],
    },
    "manuals": {
        "headers": [
            "USER MANUAL",
            "INSTRUCTION MANUAL",
            "INSTRUKCJA OBSŁUGI",
            "PODRĘCZNIK UŻYTKOWNIKA",
            "TECHNICAL GUIDE",
            "PRZEWODNIK TECHNICZNY",
            "QUICK START GUIDE",
            "SETUP GUIDE",
            "INSTALLATION GUIDE",
            "OWNER'S MANUAL",
            "Table of Contents",
            "Spis treści",
            "Chapter",
            "Rozdział",
            "Warning",
            "Ostrzeżenie",
        ],
        "vocab": [
            "manual",
            "instrukcja",
            "guide",
            "przewodnik",
            "installation",
            "instalacja",
            "setup",
            "konfiguracja",
            "troubleshooting",
            "rozwiązywanie problemów",
            "maintenance",
            "konserwacja",
            "safety",
            "bezpieczeństwo",
            "warning",
            "ostrzeżenie",
            "caution",
            "uwaga",
            "step",
            "krok",
            "procedure",
            "procedura",
            "button",
            "przycisk",
            "display",
            "wyświetlacz",
            "power",
            "zasilanie",
            "battery",
            "bateria",
            "reset",
            "firmware",
            "update",
            "aktualizacja",
            "warranty",
            "gwarancja",
            "technical specifications",
            "dane techniczne",
        ],
        "phrases": [
            "User Manual — Model XR-500 Wireless Router — Version 3.2",
            "Table of Contents: 1. Safety Instructions  2. Package Contents  3. Installation",
            "WARNING: Do not expose this device to water or excessive humidity.",
            "Step 1: Connect the power adapter to the device and plug into a wall outlet.",
            "Step 2: Press and hold the RESET button for 10 seconds to restore factory settings.",
            "Troubleshooting: If the device does not power on, check the power cable connection.",
            "Technical Specifications: Input voltage 100-240V AC, Frequency 50/60Hz, Power 12W",
            "Instrukcja obsługi — Model XR-500 Router bezprzewodowy — Wersja 3.2",
            "Spis treści: 1. Instrukcje bezpieczeństwa  2. Zawartość opakowania  3. Instalacja",
            "OSTRZEŻENIE: Nie narażać urządzenia na działanie wody ani nadmiernej wilgoci.",
            "Krok 1: Podłącz zasilacz do urządzenia i do gniazdka elektrycznego.",
            "Krok 2: Naciśnij i przytrzymaj przycisk RESET przez 10 sekund, aby przywrócić ustawienia fabryczne.",
            "Rozwiązywanie problemów: Jeśli urządzenie nie włącza się, sprawdź połączenie kabla zasilającego.",
            "Dane techniczne: Napięcie wejściowe 100-240V AC, Częstotliwość 50/60Hz, Moc 12W",
        ],
    },
    "patents": {
        "headers": [
            "PATENT",
            "PATENT APPLICATION",
            "ZGŁOSZENIE PATENTOWE",
            "OPIS PATENTOWY",
            "CLAIMS",
            "ZASTRZEŻENIA PATENTOWE",
            "ABSTRACT",
            "STRESZCZENIE",
            "FIELD OF THE INVENTION",
            "DZIEDZINA WYNALAZKU",
            "BACKGROUND OF THE INVENTION",
            "OPIS WYNALAZKU",
            "SUMMARY OF THE INVENTION",
            "BRIEF DESCRIPTION OF DRAWINGS",
        ],
        "vocab": [
            "patent",
            "invention",
            "wynalazek",
            "claim",
            "zastrzeżenie",
            "embodiment",
            "wykonanie",
            "prior art",
            "stan techniki",
            "novelty",
            "nowość",
            "inventive step",
            "poziom wynalazczy",
            "assignee",
            "zgłaszający",
            "inventor",
            "wynalazca",
            "priority date",
            "data pierwszeństwa",
            "filing date",
            "data zgłoszenia",
            "patent office",
            "urząd patentowy",
            "EPO",
            "USPTO",
            "PCT",
            "claims",
            "dependent claim",
            "zastrzeżenie zależne",
            "independent claim",
            "zastrzeżenie niezależne",
            "drawings",
            "rysunki",
            "specification",
            "opis",
            "disclosure",
            "ujawnienie",
        ],
        "phrases": [
            "Patent Application No. PCT/PL2024/000123 — Filing date: 15 January 2024",
            "Inventors: Jan Kowalski, Anna Nowak — Assignee: ACME Technologies Sp. z o.o.",
            "FIELD OF THE INVENTION: The present invention relates to a method and apparatus for wireless data transmission.",
            "BACKGROUND: Existing solutions suffer from high latency and limited bandwidth.",
            "SUMMARY: The invention provides a novel method that overcomes the prior art limitations.",
            "CLAIM 1: A method for wireless data transmission comprising the steps of: (a) encoding data...",
            "CLAIM 2 (dependent on claim 1): The method of claim 1, wherein the encoding step comprises...",
            "ABSTRACT: A method and system for low-latency wireless data transmission using adaptive modulation.",
            "Numer zgłoszenia: PCT/PL2024/000123, data zgłoszenia: 15 stycznia 2024 r.",
            "Wynalazcy: Jan Kowalski, Anna Nowak — Zgłaszający: ACME Technologies Sp. z o.o.",
            "DZIEDZINA WYNALAZKU: Wynalazek dotyczy metody i urządzenia do bezprzewodowej transmisji danych.",
            "ZASTRZEŻENIE 1: Metoda bezprzewodowej transmisji danych obejmująca etapy: (a) kodowania danych...",
            "STRESZCZENIE: Metoda i system do niskoopóźnieniowej transmisji bezprzewodowej z adaptacyjną modulacją.",
        ],
    },
    "scientific_articles": {
        "headers": [
            "ABSTRACT",
            "INTRODUCTION",
            "METHODOLOGY",
            "RESULTS",
            "DISCUSSION",
            "CONCLUSION",
            "REFERENCES",
            "KEYWORDS",
            "LITERATURE REVIEW",
            "Journal of",
            "Proceedings of",
            "DOI:",
            "ISSN",
            "Vol.",
            "Received:",
            "Accepted:",
        ],
        "vocab": [
            "abstract",
            "hypothesis",
            "methodology",
            "experiment",
            "dataset",
            "analysis",
            "results",
            "conclusion",
            "citation",
            "reference",
            "peer-reviewed",
            "journal",
            "conference",
            "proceedings",
            "DOI",
            "ISSN",
            "author",
            "affiliation",
            "university",
            "research",
            "study",
            "sample",
            "statistical",
            "p-value",
            "correlation",
            "regression",
            "significant",
            "control group",
            "variable",
            "algorithm",
            "neural network",
            "machine learning",
            "accuracy",
            "precision",
            "recall",
            "F1 score",
        ],
        "phrases": [
            "Abstract: This paper presents a novel approach to natural language processing using transformer architectures.",
            "Keywords: deep learning, NLP, transformer, attention mechanism, BERT",
            "DOI: 10.1234/journal.2024.001 — Received: 10 Jan 2024 — Accepted: 5 Mar 2024",
            "Published in: Journal of Artificial Intelligence Research, Vol. 72, pp. 123-145, 2024",
            "Authors: A. Kowalski¹, B. Nowak² — ¹University of Warsaw, ²Warsaw University of Technology",
            "1. Introduction: Recent advances in deep learning have revolutionised natural language understanding.",
            "2. Methodology: We trained our model on a corpus of 10 million documents using NVIDIA A100 GPUs.",
            "3. Results: Our method achieved 94.3% accuracy on the benchmark dataset, outperforming SOTA by 2.1%.",
            "4. Discussion: The results indicate that larger pre-training corpora significantly improve downstream performance.",
            "5. Conclusion: We proposed a new architecture that achieves state-of-the-art results with 30% fewer parameters.",
            "References: [1] Vaswani et al. (2017) Attention is all you need. NeurIPS. [2] Devlin et al. (2018) BERT.",
            "The p-value was < 0.001, confirming statistical significance of the observed performance differences.",
            "Table 1: Comparison of F1 scores across baseline models and the proposed approach.",
        ],
    },
    "lawsuits": {
        "headers": [
            "POZEW",
            "CLAIM FORM",
            "STATEMENT OF CLAIM",
            "POZEW CYWILNY",
            "POZEW O ZAPŁATĘ",
            "SĄD REJONOWY",
            "SĄD OKRĘGOWY",
            "DISTRICT COURT",
            "COURT OF APPEAL",
            "Plaintiff",
            "Powód",
            "Defendant",
            "Pozwany",
            "Case No.",
            "Sygnatura akt",
        ],
        "vocab": [
            "pozew",
            "powód",
            "pozwany",
            "sąd",
            "court",
            "plaintiff",
            "defendant",
            "claim",
            "roszczenie",
            "damages",
            "odszkodowanie",
            "hearing",
            "rozprawa",
            "judgment",
            "wyrok",
            "ruling",
            "postanowienie",
            "appeal",
            "apelacja",
            "evidence",
            "dowód",
            "witness",
            "świadek",
            "attorney",
            "pełnomocnik",
            "legal representation",
            "reprezentacja prawna",
            "court fee",
            "opłata sądowa",
            "injunction",
            "zabezpieczenie",
            "summons",
            "wezwanie",
            "complaint",
            "skarga",
            "jurisdiction",
            "właściwość sądu",
        ],
        "phrases": [
            "POZEW O ZAPŁATĘ złożony do Sądu Rejonowego dla m.st. Warszawy, Wydział Cywilny",
            "Powód: Jan Kowalski, ul. Polna 12, 00-001 Warszawa, PESEL 85012712345",
            "Pozwany: ACME Sp. z o.o., ul. Przemysłowa 5, 02-001 Warszawa, NIP 525-000-00-00",
            "Wartość przedmiotu sporu: 25 000,00 PLN",
            "Żądanie pozwu: Powód wnosi o zasądzenie od Pozwanego kwoty 25 000,00 PLN wraz z odsetkami ustawowymi.",
            "Uzasadnienie: W dniu 15 marca 2024 r. strony zawarły umowę nr 12/2024.",
            "Pozwany nie wykonał zobowiązania umownego i odmówił zapłaty wynagrodzenia.",
            "Na podstawie art. 471 k.c. powód domaga się odszkodowania za nienależyte wykonanie umowy.",
            "Dowody: 1. Umowa z dnia 15.03.2024 — Załącznik nr 1; 2. Faktury VAT — Załącznik nr 2",
            "Wniosek o zabezpieczenie roszczenia na podstawie art. 730 k.p.c.",
            "Opłata sądowa: 1 250,00 PLN (5% wartości przedmiotu sporu).",
            "Statement of Claim filed in the District Court for the capital city of Warsaw, Civil Division",
            "The Plaintiff claims damages of PLN 25,000 arising from breach of contract dated 15 March 2024.",
            "Jurisdiction: The court has jurisdiction pursuant to Article 31 of the Code of Civil Procedure.",
        ],
    },
    "power_of_attorney": {
        "headers": [
            "PEŁNOMOCNICTWO",
            "POWER OF ATTORNEY",
            "UPOWAŻNIENIE",
            "AUTHORIZATION",
            "PEŁNOMOCNICTWO OGÓLNE",
            "PEŁNOMOCNICTWO SZCZEGÓLNE",
            "PEŁNOMOCNICTWO NOTARIALNE",
            "General Power of Attorney",
            "Special Power of Attorney",
            "Mocodawca",
            "Principal",
            "Pełnomocnik",
            "Attorney-in-Fact",
        ],
        "vocab": [
            "pełnomocnictwo",
            "mocodawca",
            "pełnomocnik",
            "power of attorney",
            "principal",
            "attorney",
            "authorize",
            "upoważnienie",
            "represent",
            "reprezentować",
            "act on behalf",
            "działać w imieniu",
            "sign",
            "podpisać",
            "notary",
            "notariusz",
            "revoke",
            "odwołać",
            "substitution",
            "substytucja",
            "scope",
            "zakres",
            "legal capacity",
            "zdolność do czynności prawnych",
            "PESEL",
            "NIP",
            "identity document",
            "dowód osobisty",
            "legal entity",
            "osoba prawna",
            "notarial deed",
            "akt notarialny",
        ],
        "phrases": [
            "PEŁNOMOCNICTWO OGÓLNE udzielone w Warszawie dnia 15 marca 2024 r.",
            "Ja, Jan Kowalski, PESEL 85012712345, zamieszkały ul. Polna 12, 00-001 Warszawa,",
            "niniejszym upoważniam Annę Nowak, PESEL 90030512345, do reprezentowania mnie",
            "we wszelkich sprawach związanych z prowadzeniem działalności gospodarczej.",
            "Pełnomocnik uprawniony jest do podpisywania umów, składania oświadczeń woli,",
            "reprezentowania mocodawcy przed sądami, organami administracji publicznej i urzędami.",
            "Pełnomocnictwo obejmuje również prawo do udzielania dalszych pełnomocnictw (substytucja).",
            "Niniejsze pełnomocnictwo jest ważne bezterminowo, chyba że zostanie odwołane na piśmie.",
            "GENERAL POWER OF ATTORNEY granted in Warsaw on 15 March 2024",
            "I, Jan Kowalski, hereby authorize Anna Nowak to represent me in all matters",
            "related to the conduct of my business activities.",
            "The attorney-in-fact is authorized to sign contracts, make declarations of will,",
            "and represent the principal before courts, public administration bodies and offices.",
            "This power of attorney shall remain valid until revoked in writing by the principal.",
            "Podpis mocodawcy / Principal's signature: ________________________",
        ],
    },
    "applications": {
        "headers": [
            "WNIOSEK",
            "PODANIE",
            "APPLICATION FORM",
            "WNIOSEK O",
            "PODANIE O",
            "REQUEST FOR",
            "FORMULARZ WNIOSKU",
            "Wnioskodawca",
            "Applicant",
            "Do:",
            "To:",
            "W sprawie:",
            "Re:",
            "Data złożenia",
            "Date of submission",
        ],
        "vocab": [
            "wniosek",
            "podanie",
            "wnioskodawca",
            "applicant",
            "application",
            "request",
            "prośba",
            "organ",
            "authority",
            "urząd",
            "złożyć",
            "submit",
            "rozpatrzyć",
            "consider",
            "decyzja",
            "decision",
            "zezwolenie",
            "permit",
            "licencja",
            "license",
            "rejestracja",
            "registration",
            "zaświadczenie",
            "certificate",
            "odpis",
            "extract",
            "termin",
            "deadline",
            "uzasadnienie",
            "justification",
            "załącznik",
            "enclosure",
            "opłata",
            "fee",
            "PESEL",
            "NIP",
        ],
        "phrases": [
            "WNIOSEK O WYDANIE ZAŚWIADCZENIA złożony do Urzędu Miejskiego w Warszawie",
            "Wnioskodawca: Jan Kowalski, PESEL 85012712345, ul. Polna 12, 00-001 Warszawa",
            "Proszę o wydanie zaświadczenia o niezaleganiu w podatkach za rok 2023.",
            "Uzasadnienie: Zaświadczenie jest wymagane do udziału w postępowaniu przetargowym.",
            "Załączniki: 1. Kopia dowodu osobistego, 2. Potwierdzenie opłaty skarbowej 17,00 PLN",
            "Proszę o rozpatrzenie wniosku w ustawowym terminie 7 dni.",
            "APPLICATION FOR REGISTRATION OF BUSINESS ACTIVITY submitted to the competent authority",
            "Applicant: Jan Kowalski, PESEL 85012712345, residing at ul. Polna 12, 00-001 Warsaw",
            "I hereby request the issuance of a certificate confirming no outstanding tax liabilities.",
            "Justification: The certificate is required for participation in a public tender procedure.",
            "Enclosures: 1. Copy of identity document; 2. Proof of stamp duty payment PLN 17.00",
            "I kindly request consideration of this application within the statutory 7-day period.",
            "Wnoszę o pozytywne rozpatrzenie niniejszego podania.",
            "Z poważaniem / Yours sincerely, Jan Kowalski",
            "Data / Date: 15.03.2024  Podpis / Signature: ________________________",
        ],
    },
}


def _generate_sample(rng: random.Random, templates: dict[str, list[str]]) -> str:
    headers = rng.sample(templates["headers"], k=min(3, len(templates["headers"])))
    vocab = rng.sample(templates["vocab"], k=min(rng.randint(25, 45), len(templates["vocab"])))
    n_phrases = min(rng.randint(6, len(templates["phrases"])), len(templates["phrases"]))
    phrases = rng.sample(templates["phrases"], k=n_phrases)

    parts: list[str] = []
    parts.append(" ".join(headers).upper())
    parts.append(" ".join(phrases))
    parts.append(" ".join(vocab))
    if rng.random() < 0.5:
        parts.append(" ".join(rng.sample(vocab, k=min(10, len(vocab)))))
    rng.shuffle(parts)
    return "  ".join(parts)


def generate_split(out_dir: str, split_name: str, samples_per_class: int, seed: int) -> None:
    rng = random.Random(seed)
    for class_name, templates in _CLASS_TEMPLATES.items():
        class_dir = os.path.join(out_dir, split_name, class_name)
        os.makedirs(class_dir, exist_ok=True)
        for i in range(samples_per_class):
            text = _generate_sample(rng, templates)
            file_path = os.path.join(class_dir, f"synthetic_{i:04d}.txt")
            with open(file_path, "w", encoding="utf-8") as f:
                f.write(text)
        print(f"  {split_name}/{class_name}: generated {samples_per_class} samples")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Generate synthetic training data.")
    parser.add_argument("--out-dir", default=DEFAULT_OUT_DIR)
    parser.add_argument("--train", type=int, default=DEFAULT_TRAIN_PER_CLASS)
    parser.add_argument("--valid", type=int, default=DEFAULT_VALID_PER_CLASS)
    parser.add_argument("--seed", type=int, default=42)
    args = parser.parse_args()

    print("=" * 50)
    print(" SYNTHETIC TRAINING DATA GENERATOR")
    print("=" * 50)
    print(f" Output:  {args.out_dir}")
    print(f" Classes: {', '.join(_CLASS_TEMPLATES.keys())}")
    print(f" Train:   {args.train} samples/class")
    print(f" Valid:   {args.valid} samples/class")

    generate_split(args.out_dir, "train", args.train, args.seed)
    generate_split(args.out_dir, "valid", args.valid, args.seed + 1000)

    print("\n[OK] Done. Now run: python scripts/train_classifier.py")
